### ISSUE TITLE
Extra get args withing the language data?

### ISSUE THREAD

**Issue by goanpeca** [kra3/py-ga-mob#22]
Thanks for the awesome library.

I started including the anonimize ip and the user agent as a holder for the Operating system... but now the data in the language section is getting all these extra params.

![image](https://cloud.githubusercontent.com/assets/3627835/13559738/52df1094-e3e5-11e5-9eb3-edd4faea29e4.png)

Any thought on this?

**Comment by kra3** [comment]
@goanpeca really can't see why those extra data is getting in there.

Unless there is any change made in ga.js (and google's back-end) to help ease migration to new analytics.js library, I don't see why this happens.

However, since you are a developer you could put ipdb/logs and see the data is correct before being send to the google servers.

Data you are looking for is visitor.locale which get updated at ```visitor.extract_from_server_meta```

**Comment by goanpeca** [comment]
Thanks for the response.

I am actually not using this library anymore. The events were not working and being deprecated I switched to this [other library](https://github.com/analytics-pros/universal-analytics-python/pull/13)

Thanks
