### ISSUE TITLE
tracker.track_pageview ; sequence item 0: expected a bytes-like object, NoneType found

### ISSUE THREAD

**Issue by Vesli** [kra3/py-ga-mob#23]
Hi, I am looking forward to track the visit on an url of my django website. Url that doesn't have a page, and will have a different behaviour depending if you are on mobile or desktop.

The thing is, as I just want to know the traffic on it, I copied pasted your example (that seems to be enough for what I want) from your doc:
`tracker = Tracker('UA-XXXXX-XX', 'mydomain.com')
    visitor = Visitor()
    visitor.ip_address = '194.54.176.12'
    session = Session()
    page = Page('/en/directdownload')
    tracker.track_pageview(page, session, visitor)`

but then, when I go to the url I have this error:

> sequence item 0: expected a bytes-like object, NoneType found
Request Method:	GET
Request URL:	http://192.168.33.15:8000/en/directdownload/
Django Version:	1.7.10
Exception Type:	TypeError
Exception Value:	
sequence item 0: expected a bytes-like object, NoneType found
Exception Location:	/usr/lib/python3.4/http/client.py in putheader, line 1067

Do you have any idea about it?

**Comment by kra3** [comment]
Interesting. This won't happen in Python 2.7, but got replicated in Python 3.
I'll cross check this one.

**Comment by kra3** [comment]
@GaleDragon #20 didn't actually solved the problem.
Call to track page view is  failing at requests.py:88 where old urllib2.urlopen is replaced with
six.moves.urllib.request.urlopen for py3 compatibility.
However that call is getting failed. Our tests are also mocking urlopen call, so CI tests passed.

Please, It will be great if you can find some time out to look into this issue as you have already spend some time around it.

**Comment by kra3** [comment]
@Vesli your example failed, however in real life scenario one wouldn't be setting all the properties by themselves.

You have to call ```visitor.extract_from_server_meta``` or ```visitor.extract_from_utma``` before calling ```tracker.track_pageview(page, session, visitor)```
This calls will extract required parameters for google analytics from __utma cookie or WSGI request meta object.
And in this scenario you won't be getting the error.

@GaleDragon you can still see why the above scenario failed and find a workaround if you want.
It failed because we had a user-agent header with value of None. it worked in Py2 but not in Py3.
however I don't want to put an if check before adding each header and such an error never happens in real world scenarios.
